# Generated by Django 3.2.16 on 2023-02-03 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='troop',
            name='troop_number',
            field=models.PositiveIntegerField(),
        ),
    ]
