# Generated by Django 3.2.16 on 2023-02-03 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_animal_rfid_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='animal',
            old_name='troop',
            new_name='troop_id',
        ),
        migrations.RenameField(
            model_name='corral',
            old_name='troop',
            new_name='troop_id',
        ),
    ]
